defaults: &defaults
  docker:
    - image: circleci/openjdk:8-jdk
  working_directory: ~/repo
  environment:
    JVM_OPTS: -Xmx3200m
    TERM: dumb

version: 2
jobs:
  updatelocks:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run:
          name: Update Locks
          command: ./gradlew resolveAndLockAll --write-locks --scan --stacktrace
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - run:
          name: Build
          command: ./gradlew check shadowJar --scan --stacktrace
      - store_test_results:
          path: build/test-results

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run:
          name: Download dependencies
          command: ./gradlew dependencies --scan --stacktrace
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - run:
          name: Build
          command: ./gradlew check shadowJar --scan --stacktrace
      - store_test_results:
          path: build/test-results

workflows:
  version: 2
  updatelocks:
    jobs:
      - updatelocks
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
  build-and-release:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
